# Download needed packages

install.packages("dplyr")
install.packages("DT")
install.packages("ggplot2")
install.packages("shiny")
install.packages("shinycssloaders")
install.packages("shinyFiles")
install.packages("signal")
install.packages("terra")
install.packages("tidyr")
install.packages("tidyterra")
install.packages("purrr")
install.packages("cli")
install.packages("rlang")
install.packages("data.table")
install.packages("shinyalert")
install.packages("tibble")
install.packages("readr")
install.packages("fs")
install.packages("sf")
